name: Deploy to Render

on:
  push:
    branches:
      - main  # O la rama que desees usar para el despliegue
  pull_request:
    branches:
      - main  # Esto asegura que el flujo se ejecute cuando se cree o actualice un pull request hacia main
    types: [opened, synchronize]  # Ejecuta el flujo al abrir o actualizar un PR

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Verifica que el código se haya clonado correctamente
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # O la versión que necesites

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Ejecuta el script de build
      - name: Build the app
        run: npm run build

      # Paso 5: Despliega a Render utilizando la API
      # Solo se ejecuta cuando el evento es un push a main
      - name: Trigger Render deploy
        if: ${{ github.event_name == 'push' }}  
        run: |
          curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.API_KEY_POKEMON }}